### ISSUE TITLE
State/Region select on registration page is not correctly populated when changing the Country select field.

### ISSUE THREAD

**Issue by kalpaitch** [warmshowers/Warmshowers.org#546] opened 2015-05-11 15:49 UTC
When registering a new account and selecting an option from the Country select field there is no ajax population of the State/Region select field. Instead I am required to select the default 'NOT LISTED' option to make the form validate.

However, when I edit my account the State/Region select field is populated with the relevant options and if I do nothing to this and submit the form validation fails because my originally select value has been removed.

**Comment by rfay** [comment] 2015-05-12 00:02
This is actually a duplicate of #161, one of our oldest open issues. So annoying. The good news is that Drupal 7 is much better at AJAX updates like this and I actually contributed to a lot of that improvement based on this problem and problems like it, so hopefully we can finally get it fixed!

Reopen if I'm wrong about it being a dup.

**Closed by rfay** 2015-05-12 00:02 UTC

**Comment by kalpaitch** [comment] 2015-05-12 07:10
Correct, Dupe.
